import json
import os

BASE = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "assets", "starter")
os.makedirs(BASE, exist_ok=True)

COMMON = [
    ("hello", "xin chao", "/həˈloʊ/", "Hello, how are you?"),
    ("goodbye", "tam biet", "/ɡʊdˈbaɪ/", "Goodbye, see you tomorrow."),
    ("thank you", "cam on", "/θæŋk juː/", "Thank you for your help."),
    ("please", "lam on", "/pliːz/", "Please sit down."),
    ("yes", "co", "/jes/", "Yes, I agree."),
    ("no", "khong", "/noʊ/", "No, thank you."),
    ("water", "nuoc", "/ˈwɔːtər/", "Can I have some water?"),
    ("food", "thuc an", "/fuːd/", "The food is delicious."),
    ("time", "thoi gian", "/taɪm/", "What time is it?"),
    ("day", "ngay", "/deɪ/", "Have a nice day."),
    ("night", "dem", "/naɪt/", "Good night."),
    ("morning", "buoi sang", "/ˈmɔːrnɪŋ/", "Good morning."),
    ("friend", "ban", "/frend/", "She is my friend."),
    ("family", "gia dinh", "/ˈfæməli/", "I love my family."),
    ("work", "cong viec", "/wɜːrk/", "I go to work every day."),
    ("study", "hoc", "/ˈstʌdi/", "I study English every evening."),
    ("learn", "hoc hoi", "/lɜːrn/", "Children learn quickly."),
    ("read", "doc", "/riːd/", "I read books before bed."),
    ("write", "viet", "/raɪt/", "Please write your name here."),
    ("speak", "noi", "/spiːk/", "Do you speak English?"),
    ("listen", "nghe", "/ˈlɪsən/", "Listen carefully."),
    ("think", "suy nghi", "/θɪŋk/", "I think you are right."),
    ("know", "biet", "/noʊ/", "I know the answer."),
    ("want", "muon", "/wɒnt/", "I want to learn more."),
    ("need", "can", "/niːd/", "We need more time."),
    ("like", "thich", "/laɪk/", "I like this app."),
    ("love", "yeu", "/lʌv/", "I love learning languages."),
    ("help", "giup do", "/help/", "Can you help me?"),
    ("try", "co gang", "/traɪ/", "Try again."),
    ("use", "su dung", "/juːz/", "How do you use this?"),
    ("make", "lam", "/meɪk/", "Make a sentence."),
    ("go", "di", "/ɡoʊ/", "Let us go home."),
    ("come", "den", "/kʌm/", "Come here, please."),
    ("see", "nhin thay", "/siː/", "I see the problem."),
    ("look", "nhin", "/lʊk/", "Look at the board."),
    ("find", "tim", "/faɪnd/", "I cannot find my keys."),
    ("give", "cho", "/ɡɪv/", "Give me an example."),
    ("take", "lay", "/teɪk/", "Take your time."),
    ("get", "nhan duoc", "/ɡet/", "I get your point."),
    ("put", "dat", "/pʊt/", "Put it on the table."),
    ("big", "to", "/bɪɡ/", "This is a big house."),
    ("small", "nho", "/smɔːl/", "A small change can help."),
    ("good", "tot", "/ɡʊd/", "That is a good idea."),
    ("bad", "xau", "/bæd/", "Bad weather today."),
    ("new", "moi", "/njuː/", "I bought a new phone."),
    ("old", "cu", "/oʊld/", "An old book."),
    ("happy", "vui", "/ˈhæpi/", "I am happy today."),
    ("sad", "buon", "/sæd/", "Why are you sad?"),
    ("easy", "de", "/ˈiːzi/", "This lesson is easy."),
    ("hard", "kho", "/hɑːrd/", "English is hard but fun."),
    ("important", "quan trong", "/ɪmˈpɔːrtnt/", "Sleep is important."),
    ("different", "khac nhau", "/ˈdɪfrənt/", "We are different."),
    ("same", "giong nhau", "/seɪm/", "We have the same goal."),
    ("right", "dung", "/raɪt/", "You are right."),
    ("wrong", "sai", "/rɔːŋ/", "That answer is wrong."),
    ("question", "cau hoi", "/ˈkwestʃən/", "Ask a question."),
    ("answer", "cau tra loi", "/ˈænsər/", "What is the answer?"),
    ("problem", "van de", "/ˈprɒbləm/", "We solved the problem."),
    ("idea", "y tuong", "/aɪˈdɪə/", "That is a great idea."),
    ("money", "tien", "/ˈmʌni/", "Save money."),
    ("job", "cong viec", "/dʒɒb/", "She found a new job."),
    ("school", "truong hoc", "/skuːl/", "School starts at eight."),
    ("teacher", "giao vien", "/ˈtiːtʃər/", "The teacher is kind."),
    ("student", "hoc sinh", "/ˈstjuːdnt/", "Every student needs practice."),
    ("book", "sach", "/bʊk/", "Open your book."),
    ("word", "tu", "/wɜːrd/", "Learn one word a day."),
    ("language", "ngon ngu", "/ˈlæŋɡwɪdʒ/", "English is a global language."),
    ("country", "quoc gia", "/ˈkʌntri/", "Which country are you from?"),
    ("city", "thanh pho", "/ˈsɪti/", "I live in a big city."),
    ("home", "nha", "/hoʊm/", "I am at home."),
    ("phone", "dien thoai", "/foʊn/", "My phone is ringing."),
    ("computer", "may tinh", "/kəmˈpjuːtər/", "Use a computer to study."),
    ("internet", "mang internet", "/ˈɪntərnet/", "Search on the internet."),
    ("email", "email", "/ˈiːmeɪl/", "Send me an email."),
    ("today", "hom nay", "/təˈdeɪ/", "What are you doing today?"),
    ("tomorrow", "ngay mai", "/təˈmɒroʊ/", "See you tomorrow."),
    ("yesterday", "hom qua", "/ˈjestərdeɪ/", "I studied yesterday."),
    ("week", "tuan", "/wiːk/", "Next week is busy."),
    ("month", "thang", "/mʌnθ/", "This month I will travel."),
    ("year", "nam", "/jɪr/", "Happy new year."),
    ("always", "luon luon", "/ˈɔːlweɪz/", "Always be polite."),
    ("never", "khong bao gio", "/ˈnevər/", "Never give up."),
    ("sometimes", "thinh thoang", "/ˈsʌmtaɪmz/", "Sometimes I forget."),
    ("often", "thuong xuyen", "/ˈɒfn/", "I often practice speaking."),
    ("quickly", "nhanh", "/ˈkwɪkli/", "Finish quickly."),
    ("slowly", "cham", "/ˈsloʊli/", "Speak slowly, please."),
    ("because", "vi", "/bɪˈkɒz/", "I stayed because it rained."),
    ("but", "nhung", "/bʌt/", "I tried, but I failed."),
    ("and", "va", "/ænd/", "You and I."),
    ("or", "hoac", "/ɔːr/", "Tea or coffee?"),
    ("if", "neu", "/ɪf/", "If you study, you improve."),
    ("when", "khi", "/wen/", "When do you start?"),
    ("where", "o dau", "/weər/", "Where do you live?"),
    ("who", "ai", "/huː/", "Who is that?"),
    ("what", "gi", "/wɒt/", "What does it mean?"),
    ("why", "tai sao", "/waɪ/", "Why learn English?"),
    ("how", "the nao", "/haʊ/", "How do you say this?"),
    ("very", "rat", "/ˈveri/", "Very good job."),
    ("too", "qua", "/tuː/", "This is too difficult."),
    ("also", "cung", "/ˈɔːlsoʊ/", "I also like music."),
    ("only", "chi", "/ˈoʊnli/", "Only five minutes left."),
    ("more", "nhieu hon", "/mɔːr/", "I need more examples."),
    ("less", "it hon", "/les/", "Use less sugar."),
    ("first", "dau tien", "/fɜːrst/", "First, read the text."),
    ("last", "cuoi cung", "/læst/", "This is the last question."),
]

IELTS = [
    ("analyze", "phan tich", "/ˈænəlaɪz/", "We need to analyze the data."),
    ("approach", "cach tiep can", "/əˈproʊtʃ/", "Try a different approach."),
    ("assume", "gia dinh", "/əˈsuːm/", "Do not assume anything."),
    ("available", "co san", "/əˈveɪləbl/", "Tickets are available online."),
    ("benefit", "loi ich", "/ˈbenɪfɪt/", "Exercise has many benefits."),
    ("concept", "khai niem", "/ˈkɒnsept/", "Explain the concept clearly."),
    ("context", "ngu canh", "/ˈkɒntekst/", "Context changes meaning."),
    ("create", "tao ra", "/kriˈeɪt/", "Create a study plan."),
    ("data", "du lieu", "/ˈdeɪtə/", "Collect accurate data."),
    ("define", "dinh nghia", "/dɪˈfaɪn/", "Define your goals."),
    ("develop", "phat trien", "/dɪˈveləp/", "Develop your skills."),
    ("environment", "moi truong", "/ɪnˈvaɪrənmənt/", "Protect the environment."),
    ("establish", "thiet lap", "/ɪˈstæblɪʃ/", "Establish a routine."),
    ("evidence", "bang chung", "/ˈevɪdəns/", "There is strong evidence."),
    ("factor", "yeu to", "/ˈfæktər/", "Time is a key factor."),
    ("function", "chuc nang", "/ˈfʌŋkʃn/", "What is its function?"),
    ("global", "toan cau", "/ˈɡloʊbl/", "Global warming is serious."),
    ("identify", "xac dinh", "/aɪˈdentɪfaɪ/", "Identify the main idea."),
    ("impact", "tac dong", "/ˈɪmpækt/", "Technology has a big impact."),
    ("issue", "van de", "/ˈɪʃuː/", "Discuss the issue openly."),
    ("method", "phuong phap", "/ˈmeθəd/", "Try another method."),
    ("occur", "xay ra", "/əˈkɜːr/", "When did it occur?"),
    ("policy", "chinh sach", "/ˈpɒləsi/", "Company policy changed."),
    ("potential", "tiem nang", "/pəˈtenʃl/", "You have great potential."),
    ("process", "quy trinh", "/ˈprəʊses/", "Follow the process."),
    ("project", "du an", "/ˈprɒdʒekt/", "Start a new project."),
    ("require", "yeu cau", "/rɪˈkwaɪər/", "This task requires focus."),
    ("research", "nghien cuu", "/rɪˈsɜːtʃ/", "Do more research."),
    ("resource", "nguon luc", "/rɪˈsɔːrs/", "Use resources wisely."),
    ("response", "phan hoi", "/rɪˈspɒns/", "Wait for a response."),
    ("significant", "dang ke", "/sɪɡˈnɪfɪkənt/", "A significant improvement."),
    ("similar", "tuong tu", "/ˈsɪmələr/", "Similar results appeared."),
    ("source", "nguon", "/sɔːrs/", "Cite your sources."),
    ("specific", "cu the", "/spəˈsɪfɪk/", "Be specific in writing."),
    ("structure", "cau truc", "/ˈstrʌktʃər/", "Improve essay structure."),
    ("theory", "ly thuyet", "/ˈθɪəri/", "Theory supports practice."),
    ("trend", "xu huong", "/trend/", "Follow the latest trend."),
    ("achieve", "dat duoc", "/əˈtʃiːv/", "Achieve your target score."),
    ("alternative", "lua chon thay the", "/ɔːlˈtɜːrnətɪv/", "Consider an alternative."),
    ("community", "cong dong", "/kəˈmjuːnəti/", "Serve the community."),
    ("consequence", "he qua", "/ˈkɒnsɪkwəns/", "Face the consequences."),
    ("culture", "van hoa", "/ˈkʌltʃər/", "Respect local culture."),
    ("demonstrate", "chung minh", "/ˈdemənstreɪt/", "Demonstrate your skills."),
    ("despite", "mac du", "/dɪˈspaɪt/", "Despite rain, we went out."),
    ("enable", "cho phep", "/ɪˈneɪbl/", "This app enables practice."),
    ("ensure", "dam bao", "/ɪnˈʃʊr/", "Ensure you sleep enough."),
    ("evaluate", "danh gia", "/ɪˈvæljueɪt/", "Evaluate your progress."),
    ("fundamental", "co ban", "/ˌfʌndəˈmentl/", "Fundamental grammar rules."),
    ("generate", "tao ra", "/ˈdʒenəreɪt/", "Generate new ideas."),
    ("implement", "trien khai", "/ˈɪmplɪment/", "Implement the plan."),
    ("indicate", "chi ra", "/ˈɪndɪkeɪt/", "Results indicate progress."),
    ("investigate", "dieu tra", "/ɪnˈvestɪɡeɪt/", "Investigate the cause."),
    ("maintain", "duy tri", "/meɪnˈteɪn/", "Maintain good habits."),
    ("obtain", "dat duoc", "/əbˈteɪn/", "Obtain permission first."),
    ("participate", "tham gia", "/pɑːrˈtɪsɪpeɪt/", "Participate in class."),
    ("principle", "nguyen tac", "/ˈprɪnsəpl/", "Follow basic principles."),
    ("procedure", "thu tuc", "/prəˈsiːdʒər/", "Know the procedure."),
    ("professional", "chuyen nghiep", "/prəˈfeʃənl/", "Professional attitude."),
    ("publish", "xuat ban", "/ˈpʌblɪʃ/", "Publish your article."),
    ("relevant", "lien quan", "/ˈreləvənt/", "Stay relevant to the topic."),
    ("strategy", "chien luoc", "/ˈstrætədʒi/", "Plan your strategy."),
    ("summary", "tom tat", "/ˈsʌməri/", "Write a brief summary."),
    ("technique", "ky thuat", "/tekˈniːk/", "Use effective techniques."),
    ("tradition", "truyen thong", "/trəˈdɪʃn/", "Respect tradition."),
    ("unique", "doc dao", "/juˈniːk/", "A unique opportunity."),
    ("valid", "hop le", "/ˈvælɪd/", "A valid reason."),
    ("version", "phien ban", "/ˈvɜːrʒn/", "Latest version installed."),
    ("whereas", "trong khi", "/weərˈæz/", "Whereas I agree, he does not."),
    ("authority", "quyen luc", "/ɔːˈθɒrəti/", "Local authority approved it."),
    ("circumstance", "hoan canh", "/ˈsɜːkəmstæns/", "Under normal circumstances."),
    ("consistent", "nhat quan", "/kənˈsɪstənt/", "Be consistent with rules."),
    ("decline", "suy giam", "/dɪˈklaɪn/", "Sales declined last year."),
    ("design", "thiet ke", "/dɪˈzaɪn/", "Good design matters."),
    ("device", "thiet bi", "/dɪˈvaɪs/", "This device is portable."),
    ("economic", "kinh te", "/ˌiːkəˈnɒmɪk/", "Economic growth slowed."),
    ("element", "yeu to", "/ˈelɪmənt/", "A key element of success."),
    ("estimate", "uoc luong", "/ˈestɪmeɪt/", "Estimate the cost."),
    ("export", "xuat khau", "/ˈekspɔːrt/", "Export goods abroad."),
    ("external", "ben ngoai", "/ɪkˈstɜːrnl/", "External factors matter."),
    ("feature", "dac diem", "/ˈfiːtʃər/", "A useful feature."),
    ("finance", "tai chinh", "/ˈfaɪnæns/", "Study personal finance."),
    ("formula", "cong thuc", "/ˈfɔːrmjələ/", "Learn the formula."),
    ("hypothesis", "gia thuyet", "/haɪˈpɒθəsɪs/", "Test the hypothesis."),
    ("individual", "ca nhan", "/ˌɪndɪˈvɪdʒuəl/", "Every individual is unique."),
    ("initial", "ban dau", "/ɪˈnɪʃl/", "Initial results look good."),
    ("interpret", "giai thich", "/ɪnˈtɜːrprət/", "Interpret the chart."),
    ("legal", "hop phap", "/ˈliːɡl/", "Seek legal advice."),
    ("major", "chinh", "/ˈmeɪdʒər/", "A major decision."),
    ("period", "giai doan", "/ˈpɪəriəd/", "During this period."),
    ("proportion", "ti le", "/prəˈpɔːrʃn/", "A large proportion agreed."),
    ("region", "vung", "/ˈriːdʒən/", "A rural region."),
    ("role", "vai tro", "/roʊl/", "Play an active role."),
    ("section", "phan", "/ˈsekʃn/", "Read section two."),
    ("transfer", "chuyen", "/trænsˈfɜːr/", "Transfer the file."),
    ("variety", "da dang", "/vəˈraɪəti/", "Eat a variety of foods."),
    ("volume", "khoi luong", "/ˈvɒljuːm/", "Volume increased sharply."),
]

DAILY = [
    ("appointment", "cuoc hen", "/əˈpɔɪntmənt/", "I have a doctor appointment."),
    ("arrive", "den noi", "/əˈraɪv/", "We arrive at noon."),
    ("borrow", "muon", "/ˈbɒroʊ/", "Can I borrow your pen?"),
    ("breakfast", "buoi sang", "/ˈbrekfəst/", "Breakfast is ready."),
    ("bus", "xe buyt", "/bʌs/", "Take the bus to work."),
    ("calendar", "lich", "/ˈkælɪndər/", "Check the calendar."),
    ("call", "goi dien", "/kɔːl/", "Call me later."),
    ("cash", "tien mat", "/kæʃ/", "Pay in cash."),
    ("check", "kiem tra", "/tʃek/", "Check your email."),
    ("clean", "don dep", "/kliːn/", "Clean your room."),
    ("coffee", "ca phe", "/ˈkɒfi/", "Coffee or tea?"),
    ("cook", "nau an", "/kʊk/", "I cook dinner at home."),
    ("customer", "khach hang", "/ˈkʌstəmər/", "The customer is waiting."),
    ("deliver", "giao hang", "/dɪˈlɪvər/", "Deliver the package today."),
    ("discount", "giam gia", "/ˈdɪskaʊnt/", "There is a ten percent discount."),
    ("doctor", "bac si", "/ˈdɒktər/", "See a doctor if needed."),
    ("driver", "tai xe", "/ˈdraɪvər/", "The driver stopped the car."),
    ("exercise", "tap the duc", "/ˈeksərsaɪz/", "Exercise every morning."),
    ("flight", "chuyen bay", "/flaɪt/", "Our flight is delayed."),
    ("grocery", "cua hang tap hoa", "/ˈɡroʊsəri/", "Buy groceries after work."),
    ("guest", "khach", "/ɡest/", "We have guests tonight."),
    ("hotel", "khach san", "/hoʊˈtel/", "Book a hotel online."),
    ("invoice", "hoa don", "/ˈɪnvɔɪs/", "Pay the invoice."),
    ("kitchen", "bep", "/ˈkɪtʃɪn/", "She is in the kitchen."),
    ("laundry", "giat ui", "/ˈlɔːndri/", "Do the laundry on Sunday."),
    ("lunch", "buoi trua", "/lʌntʃ/", "Let us have lunch together."),
    ("manager", "quan ly", "/ˈmænɪdʒər/", "Ask the manager."),
    ("meeting", "cuoc hop", "/ˈmiːtɪŋ/", "The meeting starts at nine."),
    ("menu", "thuc don", "/ˈmenjuː/", "May I see the menu?"),
    ("message", "tin nhan", "/ˈmesɪdʒ/", "Leave a message."),
    ("neighbor", "hang xom", "/ˈneɪbər/", "My neighbor is friendly."),
    ("office", "van phong", "/ˈɒfɪs/", "I work in an office."),
    ("order", "dat hang", "/ˈɔːrdər/", "I would like to order coffee."),
    ("passport", "ho chieu", "/ˈpæspɔːrt/", "Bring your passport."),
    ("payment", "thanh toan", "/ˈpeɪmənt/", "Payment is due today."),
    ("pharmacy", "nha thuoc", "/ˈfɑːrməsi/", "Buy medicine at the pharmacy."),
    ("polite", "lich su", "/pəˈlaɪt/", "Be polite to staff."),
    ("receipt", "bien lai", "/rɪˈsiːt/", "Keep the receipt."),
    ("repair", "sua chua", "/rɪˈper/", "Repair the broken chair."),
    ("restaurant", "nha hang", "/ˈrestrɒnt/", "This restaurant is popular."),
    ("schedule", "lich trinh", "/ˈskedʒuːl/", "Check your schedule."),
    ("shopping", "mua sam", "/ˈʃɒpɪŋ/", "We go shopping on weekends."),
    ("signature", "chu ky", "/ˈsɪɡnətʃər/", "Sign your signature here."),
    ("station", "nha ga", "/ˈsteɪʃn/", "Meet me at the station."),
    ("subway", "tau dien ngam", "/ˈsʌbweɪ/", "Take the subway downtown."),
    ("supermarket", "sieu thi", "/ˈsuːpərmɑːrkɪt/", "The supermarket is nearby."),
    ("ticket", "ve", "/ˈtɪkɪt/", "Buy a ticket online."),
    ("traffic", "giao thong", "/ˈtræfɪk/", "Traffic is heavy today."),
    ("train", "tau hoa", "/treɪn/", "The train leaves at six."),
    ("travel", "du lich", "/ˈtrævl/", "I love to travel."),
    ("vacation", "ky nghi", "/veɪˈkeɪʃn/", "We plan a vacation."),
    ("waiter", "phuc vu", "/ˈweɪtər/", "The waiter brought water."),
    ("weather", "thoi tiet", "/ˈweðər/", "The weather is nice."),
    ("address", "dia chi", "/əˈdres/", "What is your address?"),
    ("airport", "san bay", "/ˈerpɔːrt/", "Go to the airport early."),
    ("bag", "tui", "/bæɡ/", "Pack your bag."),
    ("bank", "ngan hang", "/bæŋk/", "Open a bank account."),
    ("bathroom", "phong tam", "/ˈbæθruːm/", "Where is the bathroom?"),
    ("bedroom", "phong ngu", "/ˈbedruːm/", "The bedroom is upstairs."),
    ("bill", "hoa don", "/bɪl/", "Can we have the bill?"),
    ("birthday", "sinh nhat", "/ˈbɜːrθdeɪ/", "Happy birthday!"),
    ("boss", "sep", "/bɒs/", "My boss is supportive."),
    ("break", "nghi giai lao", "/breɪk/", "Take a short break."),
    ("building", "toa nha", "/ˈbɪldɪŋ/", "A tall building."),
    ("cab", "taxi", "/kæb/", "Call a cab."),
    ("card", "the", "/kɑːrd/", "Pay by card."),
    ("chair", "ghe", "/tʃer/", "Sit on the chair."),
    ("class", "lop hoc", "/klæs/", "English class at five."),
    ("clock", "dong ho", "/klɒk/", "The clock is slow."),
    ("colleague", "dong nghiep", "/ˈkɒliːɡ/", "My colleague helped me."),
    ("complaint", "khieu nai", "/kəmˈpleɪnt/", "File a complaint politely."),
    ("conversation", "cuoc tro chuyen", "/ˌkɒnvərˈseɪʃn/", "Start a conversation."),
    ("cost", "chi phi", "/kɒst/", "What is the total cost?"),
    ("course", "khoa hoc", "/kɔːrs/", "Join an online course."),
    ("deadline", "han chot", "/ˈdedlaɪn/", "Meet the deadline."),
    ("delivery", "giao hang", "/dɪˈlɪvəri/", "Free delivery today."),
    ("direction", "huong dan", "/dəˈrekʃn/", "Ask for directions."),
    ("document", "tai lieu", "/ˈdɒkjumənt/", "Sign the document."),
    ("emergency", "tinh huong khan cap", "/ɪˈmɜːrdʒənsi/", "Call emergency services."),
    ("entrance", "loi vao", "/ˈentrəns/", "Use the main entrance."),
    ("explain", "giai thich", "/ɪkˈspleɪn/", "Explain it simply."),
    ("favorite", "yeu thich", "/ˈfeɪvərɪt/", "What is your favorite food?"),
    ("feedback", "phan hoi", "/ˈfiːdbæk/", "We welcome feedback."),
    ("foreign", "nuoc ngoai", "/ˈfɒrən/", "Foreign languages are useful."),
    ("form", "mau don", "/fɔːrm/", "Fill out the form."),
    ("gift", "qua tang", "/ɡɪft/", "Buy a gift."),
    ("habit", "thoi quen", "/ˈhæbɪt/", "Build good habits."),
    ("health", "suc khoe", "/helθ/", "Health comes first."),
    ("holiday", "ngay le", "/ˈhɒlədeɪ/", "Enjoy the holiday."),
    ("information", "thong tin", "/ˌɪnfərˈmeɪʃn/", "Need more information."),
    ("interview", "phong van", "/ˈɪntərvjuː/", "Prepare for the interview."),
    ("invitation", "loi moi", "/ˌɪnvɪˈteɪʃn/", "Accept the invitation."),
    ("journey", "hanh trinh", "/ˈdʒɜːrni/", "Safe journey!"),
    ("key", "chia khoa", "/kiː/", "I lost my key."),
    ("leave", "roi di", "/liːv/", "What time do you leave?"),
    ("letter", "thu", "/ˈletər/", "Write a letter."),
    ("location", "vi tri", "/loʊˈkeɪʃn/", "Share your location."),
    ("luggage", "hanh ly", "/ˈlʌɡɪdʒ/", "Check your luggage."),
    ("map", "ban do", "/mæp/", "Use a map."),
    ("market", "cho", "/ˈmɑːrkɪt/", "Visit the local market."),
    ("medicine", "thuoc", "/ˈmedsn/", "Take medicine after meals."),
    ("minute", "phut", "/ˈmɪnɪt/", "Wait a minute."),
    ("mistake", "loi sai", "/mɪˈsteɪk/", "Learn from mistakes."),
    ("museum", "bao tang", "/mjuˈziːəm/", "The museum is closed Monday."),
    ("news", "tin tuc", "/njuːz/", "Good news today."),
    ("offer", "de nghi", "/ˈɒfər/", "Thank you for the offer."),
    ("opinion", "y kien", "/əˈpɪnjən/", "In my opinion, practice helps."),
    ("package", "goi hang", "/ˈpækɪdʒ/", "Track your package."),
    ("park", "cong vien", "/pɑːrk/", "Walk in the park."),
    ("password", "mat khau", "/ˈpæswɜːrd/", "Choose a strong password."),
    ("permission", "su cho phep", "/pərˈmɪʃn/", "Ask for permission."),
    ("picture", "hinh anh", "/ˈpɪktʃər/", "Send a picture."),
    ("plan", "ke hoach", "/plæn/", "Make a plan."),
    ("platform", "san ga", "/ˈplætfɔːrm/", "Wait on platform two."),
    ("price", "gia", "/praɪs/", "The price is fair."),
    ("product", "san pham", "/ˈprɒdʌkt/", "This product is new."),
    ("promise", "loi hua", "/ˈprɒmɪs/", "Keep your promise."),
    ("public", "cong cong", "/ˈpʌblɪk/", "Use public transport."),
    ("quality", "chat luong", "/ˈkwɒləti/", "High quality service."),
    ("queue", "hang doi", "/kjuː/", "Join the queue."),
    ("reason", "ly do", "/ˈriːzn/", "What is the reason?"),
    ("recommend", "gioi thieu", "/ˌrekəˈmend/", "I recommend this book."),
    ("remember", "nho", "/rɪˈmembər/", "Remember to practice."),
    ("rent", "thue", "/rent/", "Rent an apartment."),
    ("repeat", "lap lai", "/rɪˈpiːt/", "Please repeat that."),
    ("report", "bao cao", "/rɪˈpɔːrt/", "Submit the report."),
    ("request", "yeu cau", "/rɪˈkwest/", "Send a request."),
    ("reservation", "dat cho", "/ˌrezərˈveɪʃn/", "Make a reservation."),
    ("return", "quay lai", "/rɪˈtɜːrn/", "Return the book."),
    ("room", "phong", "/ruːm/", "Book a room."),
    ("rule", "quy tac", "/ruːl/", "Follow the rules."),
    ("safe", "an toan", "/seɪf/", "Stay safe."),
    ("sale", "giam gia", "/seɪl/", "Big sale this week."),
    ("save", "tiet kiem", "/seɪv/", "Save your work."),
    ("search", "tim kiem", "/sɜːrtʃ/", "Search online."),
    ("seat", "ghe ngoi", "/siːt/", "Is this seat free?"),
    ("service", "dich vu", "/ˈsɜːrvɪs/", "Good customer service."),
    ("share", "chia se", "/ʃer/", "Share your notes."),
    ("shop", "cua hang", "/ʃɒp/", "The shop closes at nine."),
    ("show", "cho xem", "/ʃoʊ/", "Show me how."),
    ("size", "co", "/saɪz/", "What size do you need?"),
    ("skill", "ky nang", "/skɪl/", "Practice speaking skills."),
    ("sleep", "ngu", "/sliːp/", "Sleep eight hours."),
    ("smile", "cuoi", "/smaɪl/", "Smile more often."),
    ("sorry", "xin loi", "/ˈsɒri/", "Sorry for the delay."),
    ("sound", "am thanh", "/saʊnd/", "That sounds good."),
    ("special", "dac biet", "/ˈspeʃl/", "Today is special."),
    ("start", "bat dau", "/stɑːrt/", "Start now."),
    ("stop", "dung lai", "/stɒp/", "Stop here, please."),
    ("store", "cua hang", "/stɔːr/", "The store is open."),
    ("story", "cau chuyen", "/ˈstɔːri/", "Tell me a story."),
    ("street", "duong pho", "/striːt/", "Cross the street carefully."),
    ("stress", "cang thang", "/stres/", "Manage stress well."),
    ("success", "thanh cong", "/səkˈses/", "Wish you success."),
    ("suggest", "de xuat", "/səˈdʒest/", "I suggest more practice."),
    ("support", "ho tro", "/səˈpɔːrt/", "Thank you for your support."),
    ("surprise", "bat ngo", "/sərˈpraɪz/", "What a surprise!"),
    ("table", "ban", "/ˈteɪbl/", "Set the table."),
    ("task", "nhiem vu", "/tæsk/", "Complete the task."),
    ("team", "doi nhom", "/tiːm/", "Work as a team."),
    ("telephone", "dien thoai", "/ˈtelɪfoʊn/", "Answer the telephone."),
    ("temperature", "nhiet do", "/ˈtemprətʃər/", "The temperature dropped."),
    ("test", "bai kiem tra", "/test/", "Pass the test."),
    ("text", "tin nhan", "/tekst/", "Send a text."),
    ("thing", "vat", "/θɪŋ/", "One thing at a time."),
    ("tip", "meo", "/tɪp/", "Here is a useful tip."),
    ("title", "tieu de", "/ˈtaɪtl/", "Write a clear title."),
    ("topic", "chu de", "/ˈtɒpɪk/", "Choose a topic."),
    ("total", "tong cong", "/ˈtoʊtl/", "What is the total?"),
    ("tourist", "du khach", "/ˈtʊrɪst/", "Many tourists visit."),
    ("town", "thi tran", "/taʊn/", "A small town."),
    ("translate", "dich", "/trænsˈleɪt/", "Translate this sentence."),
    ("trip", "chuyen di", "/trɪp/", "Have a safe trip."),
    ("turn", "re", "/tɜːrn/", "Turn left."),
    ("useful", "huu ich", "/ˈjuːsfl/", "Very useful phrase."),
    ("visit", "tham", "/ˈvɪzɪt/", "Visit us soon."),
    ("voice", "giong noi", "/vɔɪs/", "Speak with a clear voice."),
    ("walk", "di bo", "/wɔːk/", "Walk to school."),
    ("wallet", "vi tien", "/ˈwɒlɪt/", "I lost my wallet."),
    ("wash", "rua", "/wɒʃ/", "Wash your hands."),
    ("watch", "xem", "/wɒtʃ/", "Watch a movie."),
    ("website", "trang web", "/ˈwebsaɪt/", "Visit our website."),
    ("welcome", "chao mung", "/ˈwelkəm/", "Welcome aboard."),
    ("window", "cua so", "/ˈwɪndoʊ/", "Open the window."),
    ("wish", "uoc", "/wɪʃ/", "Best wishes."),
    ("world", "the gioi", "/wɜːrld/", "Travel the world."),
    ("worry", "lo lang", "/ˈwʌri/", "Do not worry."),
]


def cefr_for_index(index, total, pack_id):
    ratio = index / max(total, 1)
    if pack_id == "common_100":
        if ratio < 0.45:
            return "A1"
        if ratio < 0.75:
            return "A2"
        return "B1"
    if pack_id == "daily_communication":
        if ratio < 0.35:
            return "A2"
        if ratio < 0.65:
            return "B1"
        return "B2"
    if pack_id == "ielts_starter":
        if ratio < 0.35:
            return "B1"
        if ratio < 0.65:
            return "B2"
        return "C1"
    return "B1"


def write_csv(path, rows, pack_id):
    with open(path, "w", encoding="utf-8") as f:
        f.write("word,meaning,pronunciation,example,cefr\n")
        total = len(rows)
        for i, (word, meaning, pron, example) in enumerate(rows):
            example = example.replace('"', '""')
            cefr = cefr_for_index(i, total, pack_id)
            f.write(f'{word},{meaning},{pron},"{example}",{cefr}\n')


write_csv(os.path.join(BASE, "common_100.csv"), COMMON, "common_100")
write_csv(os.path.join(BASE, "ielts_starter.csv"), IELTS, "ielts_starter")
write_csv(os.path.join(BASE, "daily_communication.csv"), DAILY, "daily_communication")

packs = [
    {
        "id": "common_100",
        "title": "100 từ thường gặp",
        "description": "Từ vựng cơ bản để bắt đầu học ngay.",
        "fileName": "common_100.csv",
        "tags": "starter,beginner",
        "autoInstall": True,
    },
    {
        "id": "ielts_starter",
        "title": "IELTS Starter",
        "description": "Từ học thuật thường gặp trong IELTS.",
        "fileName": "ielts_starter.csv",
        "tags": "starter,ielts",
        "autoInstall": False,
    },
    {
        "id": "daily_communication",
        "title": "Giao tiếp hằng ngày",
        "description": "Cụm từ và từ dùng trong đời sống hàng ngày.",
        "fileName": "daily_communication.csv",
        "tags": "starter,daily",
        "autoInstall": False,
    },
]
with open(os.path.join(BASE, "packs.json"), "w", encoding="utf-8") as f:
    json.dump(packs, f, ensure_ascii=False, indent=2)

print("counts", len(COMMON), len(IELTS), len(DAILY))
